// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49d0_noGU7VOiMHXPvk1hD7R4jHtFtVs',
    appId: '1:1033567411627:web:ffe1b8bc0009dbc0be06ee',
    messagingSenderId: '1033567411627',
    projectId: 'reelsapp-760cf',
    authDomain: 'reelsapp-760cf.firebaseapp.com',
    storageBucket: 'reelsapp-760cf.firebasestorage.app',
    measurementId: 'G-74ZM6B1WHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaKjw1LBtGslyw9ViWjLmN_hjTZwFARU',
    appId: '1:1033567411627:android:02a072c29fa3c5ccbe06ee',
    messagingSenderId: '1033567411627',
    projectId: 'reelsapp-760cf',
    storageBucket: 'reelsapp-760cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANHZHjHFWqIE121-M07bSkLNYDsbBnSY',
    appId: '1:1033567411627:ios:4f6dec977bde1ed4be06ee',
    messagingSenderId: '1033567411627',
    projectId: 'reelsapp-760cf',
    storageBucket: 'reelsapp-760cf.firebasestorage.app',
    iosBundleId: 'com.example.reelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCANHZHjHFWqIE121-M07bSkLNYDsbBnSY',
    appId: '1:1033567411627:ios:4f6dec977bde1ed4be06ee',
    messagingSenderId: '1033567411627',
    projectId: 'reelsapp-760cf',
    storageBucket: 'reelsapp-760cf.firebasestorage.app',
    iosBundleId: 'com.example.reelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB49d0_noGU7VOiMHXPvk1hD7R4jHtFtVs',
    appId: '1:1033567411627:web:5f24e3b2a2306706be06ee',
    messagingSenderId: '1033567411627',
    projectId: 'reelsapp-760cf',
    authDomain: 'reelsapp-760cf.firebaseapp.com',
    storageBucket: 'reelsapp-760cf.firebasestorage.app',
    measurementId: 'G-17P4K1DCX1',
  );
}
